# -*- coding: utf-8 -*-
"""image to text extraction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/144QeqZs1RfCTr8bbTDPsVDi75uxPX3NB
"""

import cv2
import matplotlib.pyplot as plt
import os

# Read the image using OpenCV
image_path = '/Narmadha_G (1).jpg'
# Check if the file exists
if not os.path.exists(image_path):
    print(f"Error: The file '{image_path}' does not exist.")
else:
    image_original = cv2.imread(image_path)

    # Check if the image was loaded correctly
    if image_original is None:
        print(f"Error: Failed to load the image from '{image_path}'.")
    else:
        # Convert the image from BGR to RGB format
        image_rgb = cv2.cvtColor(image_original, cv2.COLOR_BGR2RGB)

        # Display the image using matplotlib
        plt.imshow(image_rgb)
        plt.axis("off")
        plt.show()

!apt install tesseract-ocr
!pip install pytesseract
import os
import cv2
import shutil
import random
import pytesseract
try:
    from PIL import Image
except ImportError:
     import Image

import numpy as np
import matplotlib.pyplot as plt

image_path_in_colab=image_path
extractedInformation = pytesseract.image_to_string(Image.open(image_path_in_colab))
print(extractedInformation)